server:
  port: 8000
spring:
  application:
    name: user-authentication
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/priceCommunicationSystem?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8040/eureka/
  instance:
    prefer-ip-address: true